# 設定ファイルの非公開版。ローカル実行時に使用されます。
# Private version of the configuration file. Used for local execution.

notification:
  year: ""
  month: ""
  day: ""
  to: ""

husband:
  last_name: ""
  last_name_pos: [220,590]
  last_name_kana: ""
  last_name_kana_pos: [221,623]
  first_name: ""
  first_name_pos: [300,590]
  first_name_kana: ""
  first_name_kana_pos: [305,623]
  birth_year: ""
  birth_month: ""
  birth_day: ""
  address_first: ""
  address_first_pos: [221, 545]
  address_second: ""
  is_banchi_address: false
  address_go: ""
  address_apartment: | # 3行までであれば崩れず表現できます
    ""
  household_person: ""
  legally_domiciled_first: ""
  legally_domiciled_first_pos: [221, 480]
  legally_domiciled_second: ""
  is_banchi_legally_domiciled: false
  head_of_person_of_legally_domiciled: ""
  father_name: ""
  father_name_pos: [221, 410]
  mother_name: ""
  mother_name_pos: [221, 380]
  relationship: ""
  marital_history:
    marriage_cat: 0 # 0: 初婚 1:死別 2:離別
    year: ""
    month: ""
    day: ""
  job_type: 0

wife:
  last_name: ""
  last_name_pos: [420,590]
  last_name_kana: ""
  last_name_kana_pos: [421,623]
  first_name: ""
  first_name_pos: [502,590]
  first_name_kana: ""
  first_name_kana_pos: [502,623]
  birth_year: ""
  birth_month: ""
  birth_day: ""
  address_first: ""
  address_first_pos: [422, 545]
  address_second: ""
  is_banchi_address: false
  address_go: ""
  address_apartment: |
    ""
  household_person: ""
  legally_domiciled_first: ""
  legally_domiciled_first_pos: [421, 480]
  legally_domiciled_second: ""
  is_banchi_legally_domiciled: false
  head_of_person_of_legally_domiciled: ""
  father_name: ""
  father_name_pos: [421, 410]
  mother_name: ""
  mother_name_pos: [421, 380]
  relationship: ""
  marital_history:
    marriage_cat: 0 # 0: 初婚 1:死別 2:離別
    year: ""
    month: ""
    day: ""
  job_type: 0

new_legally_domiciled:
  is_husband_lastname: true
  address: ""
  address_pos: [251, 335]
  is_banchi_address: false

to_live_together:
  year: ""
  month: ""

national_census: # 国勢調査の年4/1-翌3/31に該当しない場合は記載不要。yearを空白文字""に
  year: ""
  husband_job: ""
  wife_job: ""

other: # 旧字体<=>新字体の変更などで使用。未成年婚姻のような同意欄の場合は直筆推奨で、必ず捺印を行うこと
  text: |
    ""
